spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway-client:
            issuer-uri: http://localhost:8080/realms/spring-boot-ream-dev
        registration:
          api-gateway-client:
            provider: api-gateway-client
            scope: openid
            client-id: api-gateway-client
            client-secret: hQenC95S3SwPi3V3pW5pBAIAoL284HDc
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: SpringBookKeycloak
          uri: lb://SpringBookKeycloak
          predicates:
            - Path=/keycloak/**
        - id: Accounts
          uri: http://localhost:8086/account/
          predicates:
            - Path=/account/**
        - id: Payments
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
server:
  port: 8085

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      keycloak: DEBUG
