spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/user/**
          filters:
            - AddRequestHeader=X-Response-from, gateway 
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
