spring:
  application:
    name: gateway-service
    description: microservicio de Gateway desde Github
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dh
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/user/**
          filters:
            - AddResponseHeader=X-Response-from, gateway
            - AddResponseHeader=X-Response-Red, Blue
server:
  port: 8085
eureka:
  instance:
    statusPageUrlPath: http://localhost:8085/actuator/info
    healthCheckUrlPath: http://localhost:8085/actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
