spring:
 application:
  name: gateway-service
 cloud:
  config:
   discovery:
    enable: true
    serviceId: config-server
  gateway:
   routes:
    - id: user-service
      uri: lb://user-service
      predicates:
        - Path=/user-service
server:
 port: 8085
